# Generated by Django 5.0.7 on 2024-08-21 21:51

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=50)),
                ('Page_count', models.IntegerField()),
                ('isbn', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=200)),
                ('Keyword', models.CharField(max_length=200)),
                ('Barcode', models.CharField(max_length=200, unique=True)),
                ('Publication_date', models.DateField(blank=True, null=True)),
                ('Price', models.FloatField()),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('Description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(default='UNKNOWN', max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issuedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(default=app.models.get_expiry)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('returndate', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=100)),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to='national_id_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
