# Generated by Django 5.0.7 on 2024-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_publication_place_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Cl_No',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
